---
title: "Generalized Additive Models (GAMs)"
subtitle: "CMDA 4654 Project 2"
author: "Group 19: Brady Bolton, Eryk Jesse, Charles Lee, Dan Schlicht"
output: 
  beamer_presentation:
    theme: "Rochester"
    colortheme: "beaver"
    fonttheme: "structurebold"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Generalized Additive Models

- Background (brief)
- Math stuff

$g(\operatorname {E}(Y))=\beta _{0}+f_{1}(x_{1})+f_{2}(x_{2})+\cdots +f_{m}(x_{m})$

## When to Use & Why

## Example - iris

```{r}
data("iris")
```

## Example - iris
```{r}
# Set up iris model
```

## Example - iris
```{r}
# iris model graph or whatever
```

## Example - mtcars

```{r}
data("mtcars")
```

## Example - mtcars
```{r}
# Set up mtcars model
```

## Example - mtcars
```{r}
# mtcars model graph or whatever
```

## Example - Health Data
```{r}
# df <- read.csv('health_data.csv')
 # show the data
```

## Example - Health Data
```{r}
# create the model
```

## Example - Health Data
```{r}
# show some graphs or whatever
```

## Conclusions

- Useful Libraries

## References
